name: beta-ca-ci
on:
  #push:
  #  branches: [ release ]
  pull_request:
    branches: [ beta ]
    types: [closed, opened, synchronize]
  workflow_dispatch:  
jobs:
  build:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    environment: release
    #env:
    steps:
      - uses: actions/checkout@v2
      - name: bootstrap beta
        id: bootstrap-beta
        #env:
        run: |
          echo bootstrap beta
      - name: pr merged
        if: github.event_name == 'pull_request' && github.event.action == 'closed' && github.event.pull_request.merged == true
        id: pr-merged
        run: |
          echo pr has been merged and closed
